filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - '*.min.js'
checks:
    php:
        code_rating: true
coding_style:
    php:
        spaces:
            around_operators:
                multiplicative: false
build:
    environment:
        php: 7.1.1
        mysql: 5.6
        tools:
tools:
    external_code_coverage: true
    php_analyzer: true
    php_mess_detector: true
    php_sim: true
    sensiolabs_security_checker: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }