language: php

php:
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true

before_install:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20started' >/dev/null 2>&1
  - sudo apt-get update -qq > /dev/null
  - phpenv config-rm xdebug.ini
  - composer global require "hirak/prestissimo:^0.3"
install:
  - sudo apt-get install -y --force-yes php7-mysql
  - composer -n --no-progress --no-suggest install
script:
  - vendor/bin/phpcs --colors --standard=PSR2 src/
  - vendor/bin/phpunit
after_success:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20succeeded!' >/dev/null 2>&1

after_failure:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20failed%20:(' >/dev/null 2>&1