language: php

php:
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true

before_install:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20started' >/dev/null 2>&1
  - sudo apt-get update -qq > /dev/null
  - composer global require "hirak/prestissimo:^0.3"
  - mysql -e 'CREATE DATABASE symfony;'
install:
  - composer -n --no-progress --no-suggest install
before_script: echo 'error_reporting = E_ALL ^ E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - vendor/bin/phpcs --colors --standard=PSR2 src/
  - phpunit --coverage-clover=coverage.clover
after_script:
  - wget -q https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
after_success:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20succeeded!' >/dev/null 2>&1
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
       if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
           wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar
           chmod +x rocketeer.phar
           ./rocketeer.phar deploy --no-interaction
       fi
    fi

after_failure:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20failed%20:(' >/dev/null 2>&1