language: php

php:
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true

before_install:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20started' >/dev/null 2>&1
  - sudo apt-get update -qq > /dev/null
  - composer global require "hirak/prestissimo:^0.3"
  - mysql -e 'CREATE DATABASE symfony;'
install:
  - composer -n --no-progress --no-suggest install
script:
  - vendor/bin/phpcs --colors --standard=PSR2 src/
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
after_success:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20succeeded!' >/dev/null 2>&1

after_failure:
  - wget -O - -q 'https://02p.ru/tnotify/?ntxt=Build%20of%20chrl/myhome%20failed%20:(' >/dev/null 2>&1