<?php
/**
 * Created by PhpStorm.
 * User: chrl
 * Date: 21/02/17
 * Time: 20:10
 */

namespace Tests\AppBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class LoadFixtures extends WebTestCase
{

	public function setUp()
	{

		parent::setUp(); // TODO: Change the autogenerated stub
	}
}